name: Profile Readme Development Stats
# You may pin to the exact commit or the version.
# uses: anmol098/waka-readme-stats@b2646a9af922f06b6a3cf3c3059e3bb67df077ca
uses: anmol098/waka-readme-stats@V3
  with:
    # GitHub access token with Repo scope
    GH_TOKEN: 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
    # Your Wakatime API Key
    WAKATIME_API_KEY: be378cab-d0cc-4c2b-a542-46ba643699be
